# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        article: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [ 330, 180 ] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        arti:
            quality: 80
            filters:
                upscale:
                    min: [690, 340]
                thumbnail:
                    size: [690, 340]
                    mode: outbound
                watermark:
                    image: ../public/img/LogoV1.png
                    size: 0.3
                    position: bottomright
        nft:
            quality: 75
            filters :
                thumbnail :
                    size : [360,230]
                    mode : outbound
                    allow_upscale : true