twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        user_wallet: '@App\Repository\WalletRepository'
        chat_group: '@App\Repository\GroupChatRepository'
        chat_private: '@App\Repository\PrivateChatRepository'
        chat_message: '@App\Repository\MessageRepository'
    paths:
        '%kernel.project_dir%/public/img': images

